import Head from "next/head";
import Carousel from "@/components/home/carousel/Carousel";
import CategoryRow from "@/components/home/categories/CategoryRow";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto xl:screens lg:w-10/12 md:w-screen sm:w-screen relative">
        
        {/* carousel */}
        <div className="p-8 bg-white">
          <Carousel SLIDE_LEN={2} />
          {/* <div className="bg-slate-400 h-[350px] flex items-center justify-center">
            carousel
          </div> */}
        </div>
        {/* items */}
        <div className="bg-green-100 p-4">items</div>
        <CategoryRow />
      </div>
    </>
  );
}
